name: Infection

on:
  pull_request:
  push:
    branches:
      - "master"
  workflow_dispatch:

jobs:
  Infection:
    runs-on: ubuntu-22.04

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v3"
        with:
          fetch-depth: 2

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          php-version: "8.1"
          coverage: "pcov"

      - name: "Install dependencies with Composer"
        uses: "ramsey/composer-install@v2"

      - name: Run Infection
        run: vendor/bin/roave-infection-static-analysis-plugin --threads=$(nproc)
        env:
          STRYKER_DASHBOARD_API_KEY: ${{ secrets.STRYKER_DASHBOARD_API_KEY }}
